
[[plugins]] # 缩进线
repo = 'Yggdroot/indentLine'
on_event = 'BufReadPre'
hook_source = '''
    let g:indentLine_enabled = 1
    let g:indentLine_char='│'
    let g:indentLine_fileTypeExclude = ['denite','startify','tagbar','vista_kind','vista','coc-explorer','dashboard','json','jsonc']
    let g:indentLine_concealcursor = 'niv'
	let g:vim_json_syntax_conceal = 0
'''
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
rev = 'lua'
on_source = 'indentLine'
# on_event = 'BufReadPre'
hook_source = '''
set colorcolumn=99999
    let g:indent_blankline_filetype_exclude = ['denite','startify','tagbar','vista_kind','vista','coc-explorer','dashboard','json','jsonc']
'''

[[plugins]] #注释
repo = 'tyru/caw.vim'
depends = 'context_filetype.vim'
on_map = { nx = '<Plug>' }

[[plugins]] # 函数表
repo = 'liuchengxu/vista.vim'
on_cmd = ['Vista', 'Vista!', 'Vista!!']
hook_source = '''

	let g:vista_icon_indent = ["╰─▸ ", "├─▸ "]
    let g:vista_disable_statusline = 1
    let g:vista_default_executive = 'ctags'
    let g:vista_echo_cursor_strategy = 'echo'
    let g:vista_vimwiki_executive = 'markdown'
    let g:vista_executive_for = {
		\ 'c': 'coc',
		\ 'cpp': 'coc',
		\ 'vimwiki': 'markdown',
		\ 'pandoc': 'markdown',
		\ 'markdown': 'toc',
		\ 'yaml': 'coc',
		\ 'typescript': 'coc',
		\ 'typescriptreact': 'coc',
		\ }
'''

[[plugins]] #tags
repo = 'ludovicchabant/vim-gutentags'
if = 'executable("ctags")'
on_event = ['BufReadPost', 'BufWritePost']
hook_source = '''
    let g:gutentags_cache_dir = $DATA_PATH . '/tags'
    let g:gutentags_project_root = ['.root', '.git', '.svn', '.hg', '.project','go.mod','/usr/local']
    let g:gutentags_generate_on_write = 1
    let g:gutentags_generate_on_missing = 1
    let g:gutentags_generate_on_new = 0
    let g:gutentags_exclude_filetypes = [ 'defx', 'denite', 'vista', 'magit' ]
    let g:gutentags_ctags_extra_args = ['--output-format=e-ctags']
    let g:gutentags_ctags_exclude = ['*.json', '*.js', '*.ts', '*.jsx', '*.css', '*.less', '*.sass', '*.go', '*.dart', 'node_modules', 'dist', 'vendor']
'''

