[[plugins]]
repo = 'rakr/vim-one'
[[plugins]]
repo = 'lifepillar/vim-solarized8'
[[plugins]]
repo = 'hardcoreplayers/oceanic-material'
[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'
[[plugins]]
repo = 'mhartington/oceanic-next'
[[plugins]]
repo = 'liuchengxu/space-vim-theme'
[[plugins]]
repo = 'Th3Whit3Wolf/onebuddy'
[[plugins]]
repo = 'tjdevries/colorbuddy.vim'
[[plugins]]
repo = 'Th3Whit3Wolf/one-nvim'









